### PR TITLE
Fixes #51. Chess Symbols (U+1fa00-1fa0f) not returning Column Width bigger than 1.

### LINKED ISSUE #51: Chess Symbols (U+1fa00-1fa0f) not returning Column Width bigger than 1.
Adding more Rune unit tests.

### PR DESCRIPTION
**Pull request by BDisp**

### CODE REVIEW

**Comment by migueldeicaza** [comment]
Question: the removal of ValueTuple, this will still work on .NET Framework?

**Comment by BDisp** [comment]
Yes it's working on on .NET Framework 472.

**Comment by BDisp** [comment]
@migueldeicaza I reverted the removed `System.ValueTuple` to not breaking anything. I only updated the version for the `NStack `API.

**Comment by migueldeicaza** [comment]
Uploaded, NuGet should have it available soon, version 0.16

**Comment by BDisp** [comment]
Thanks @migueldeicaza .

**Pull request merged**
