### PR TITLE
Prepping for Release v1.0.7

### PR DESCRIPTION
**Pull request by tig**

### CODE REVIEW

**Review by BDisp — APPROVED** [review]

**Comment by tig** [comment]
@BDisp did you actually test the latest NStack (1.0.6/1.0.7) on the latest Terminal.Gui `develop` branch? 

After publishing v1.0.7, and updating Terminal.Gui to use it, the unit tests are failing.

I'm going to unpublish v1.0.7 for now.

**Comment by tig** [comment]
> Yes I tried now and it's failing because of this:
> 
> `public uint HotKeyTagMask { get; set; } = 0x100000;`
> 
> Since the range from 0x10000...0x10FFFF is marked as wide characters, spaces are added after the hot keys. It's better waiting for a fix for this first.

Please explain more thoroughly. Why did your testing when you approved this PR not fail?

**Comment by BDisp** [comment]
I think the better way to fix this is by removing the `HotKeyTagMask` property and deal directly with the `HotKey` property. What do you think?

**Comment by BDisp** [comment]
Since we need to remove the hotkey if it's other than uppercase for text handling, maybe change the `uint HotKeyTagMask` property to `int HotKeyPos` property to save the hotkey position when the text is been handling for wrap, alignment or whatever and using the position to draw the hotkey properly. Well I think this will be the better option.

**Comment by BDisp** [comment]
I already fixed it. I'll submit a PR.

**Comment by BDisp** [comment]
@tig I already submitted the PR https://github.com/gui-cs/Terminal.Gui/issues/2247 with the fix. Can you republish the nuget package again, please. Without that the fix won't work.

**Pull request merged**
